---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart chesslab
  ansible.builtin.systemd:
    name: chesslab
    state: restarted
    daemon_reload: true

- name: reload traefik
  ansible.builtin.systemd:
    name: traefik
    state: restarted
