---
galaxy_info:
  role_name: livekit_deploy
  author: Jochen Wersdörfer
  description: Deploy LiveKit server and Egress with Docker Compose
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
dependencies: []
