---
# Configure Traefik for Wagtail

- name: traefik | Render Wagtail Traefik config
  ansible.builtin.include_role:
    name: local.ops_library.webapp_deploy_internal
    tasks_from: traefik_config
  vars:
    webapp_deploy_internal_traefik_template_src: "templates/wagtail.traefik.yml.j2"
    webapp_deploy_internal_traefik_dest: "{{ wagtail_traefik_config_path }}"
