---
# Vaultwarden deployment main tasks

- name: main | Validate Vaultwarden configuration
  ansible.builtin.import_tasks: validate.yml

- name: main | Configure Vaultwarden apt repository
  ansible.builtin.import_tasks: repository.yml

- name: main | Install Vaultwarden packages
  ansible.builtin.import_tasks: packages.yml

- name: main | Configure Vaultwarden
  ansible.builtin.import_tasks: configure.yml

- name: main | Configure Traefik for Vaultwarden
  ansible.builtin.import_tasks: traefik.yml
  when: vaultwarden_traefik_enabled | bool

- name: main | Ensure Vaultwarden service state
  ansible.builtin.import_tasks: service.yml

- name: main | Run Vaultwarden health check
  ansible.builtin.import_tasks: health.yml
  when: vaultwarden_healthcheck_enabled | bool
