---
# Configure Traefik for Nyxmon

- name: traefik | Render Nyxmon Traefik config
  ansible.builtin.include_role:
    name: local.ops_library.webapp_deploy_internal
    tasks_from: traefik_config
  vars:
    webapp_deploy_internal_traefik_template_src: "templates/traefik-nyxmon.yml.j2"
    webapp_deploy_internal_traefik_dest: /etc/traefik/dynamic/nyxmon.yml
    webapp_deploy_internal_traefik_basic_auth_enabled: "{{ nyxmon_basic_auth_enabled }}"
    webapp_deploy_internal_traefik_basic_auth_user: "{{ nyxmon_basic_auth_user }}"
    webapp_deploy_internal_traefik_basic_auth_password: "{{ nyxmon_basic_auth_password }}"
    webapp_deploy_internal_traefik_password_hash_var: nyxmon_basic_auth_password_hash
    webapp_deploy_internal_traefik_auth_packages: []
    webapp_deploy_internal_traefik_auth_package_os_families: []
    webapp_deploy_internal_traefik_notify_handlers:
      - reload traefik
    webapp_deploy_internal_traefik_service_name: traefik
    webapp_deploy_internal_traefik_force_restart: false
