---
- name: systemd | Render LiveKit systemd service
  ansible.builtin.template:
    src: livekit.service.j2
    dest: "/etc/systemd/system/{{ livekit_service_name }}.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload systemd
    - restart livekit

- name: systemd | Ensure LiveKit systemd service is enabled and started
  ansible.builtin.systemd:
    name: "{{ livekit_service_name }}"
    enabled: true
    state: started
    daemon_reload: true
