---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart weeknotes home
  ansible.builtin.systemd:
    name: "{{ weeknotes_home_systemd_unit_name }}"
    state: restarted
  when: weeknotes_home_service_restart_on_change | bool

- name: reload traefik
  ansible.builtin.systemd:
    name: traefik
    state: restarted
