---
- name: "Check Home Assistant Matter integration imports"
  ansible.builtin.command:
    cmd: "{{ homeassistant_virtualenv_path }}/bin/python -c 'import homeassistant.components.matter.config_flow'"
  changed_when: false

- name: "Check Matter server imports"
  ansible.builtin.command:
    cmd: "{{ homeassistant_matter_server_virtualenv_path }}/bin/python -c 'from matter_server.server.__main__ import main; from matter_server.common.custom_clusters import check_polled_attributes'"
  changed_when: false
