---
- name: config | Render delve environment file
  ansible.builtin.template:
    src: delve.env.j2
    dest: "{{ delve_env_path }}"
    owner: root
    group: "{{ delve_group }}"
    mode: "0640"
  no_log: true
  notify: restart delve
