---
# Setup systemd service for FastDeploy

- name: service | Render and enable FastDeploy systemd unit
  ansible.builtin.include_role:
    name: local.ops_library.webapp_deploy_internal
    tasks_from: systemd_service
  vars:
    webapp_deploy_internal_service_template_src: "templates/fastdeploy.service.j2"
    webapp_deploy_internal_service_unit_dest: "/etc/systemd/system/{{ fastdeploy_service_name }}.service"
    webapp_deploy_internal_service_name: "{{ fastdeploy_service_name }}"
    webapp_deploy_internal_service_notify_handlers:
      - reload systemd
      - restart fastdeploy
