---
# Setup Traefik routing for FastDeploy

- name: traefik | Render FastDeploy Traefik config
  ansible.builtin.include_role:
    name: local.ops_library.webapp_deploy_internal
    tasks_from: traefik_config
  vars:
    webapp_deploy_internal_traefik_template_src: "templates/traefik.yml.j2"
    webapp_deploy_internal_traefik_dest: "/etc/traefik/dynamic/{{ fastdeploy_service_name }}.yml"
    webapp_deploy_internal_traefik_basic_auth_enabled: "{{ fastdeploy_basic_auth_enabled }}"
    webapp_deploy_internal_traefik_basic_auth_user: "{{ fastdeploy_basic_auth_user }}"
    webapp_deploy_internal_traefik_basic_auth_password: "{{ fastdeploy_basic_auth_password }}"
    webapp_deploy_internal_traefik_password_hash_var: fastdeploy_basic_auth_password_hash
    webapp_deploy_internal_traefik_auth_packages:
      - apache2-utils
    webapp_deploy_internal_traefik_auth_package_os_families:
      - Debian
    webapp_deploy_internal_traefik_notify_handlers:
      - restart traefik
    webapp_deploy_internal_traefik_service_name: traefik
    webapp_deploy_internal_traefik_force_restart: true
